#这些是支持的资金模型平台

给我买杯咖啡替换为最多4个支持GitHub赞助商的用户名，例如[user1，user2]GitHub：##替换为最多4个支持GitHub赞助商的用户名，例如[user1，user2]
Patreon：#替换为单个Patreon用户名: #替换为单个patreon用户名
open_collective：#替换为单个打开集合用户名: #替换为单个打开集合用户名
Ko_fi：#替换为单个Ko-fi用户名: #替换为单个Ko-fi用户名
潮汐：#替换为单个潮汐升力平台-名称/包-名称，例如npm/babel: #替换为单个Tidelift平台-名称/包-名称，例如npm/babel
社区网桥(_B)：#替换为单个社区桥梁项目名称，例如Cloud-Foundry: #替换为单个社区桥项目-名称，例如Cloud-Foundry
Liberapay：#替换为单个利伯拉佩用户名: #替换为单个利伯拉佩用户名
issueHunt：#替换为单个IssueHunt用户名: #替换为单个IssueHunt用户名
LFX_crowdfunding：#替换为单个LFX众筹项目-名称，例如，Cloud-Foundry: #替换为单个LFX众筹项目-名称，如云铸造
polar：#替换为单个Polar用户名: #替换为单个Polar用户名
买咖啡：#替换为单个“请为我买一杯咖啡”用户名: #替换为单个“请给我买咖啡”用户名
tanks_dev：#替换为一个tanks.dev用户名
自定义: #替换为最多4个自定义赞助URL，例如['link1'，'link2']
