#此工作流使用未经GitHub认证的操作。
#它们由第三方提供，并由
#单独的服务条款、隐私政策和支持
#documentation。

#####################################################################################################################################################################
#使用此工作流模板作为将debricked集成到GitHub工作流中的基础。#
#                                                                                                                                                                   #
#如果您需要配置方面的其他帮助，请随时通过聊天或电子邮件与我们联系#support@debricked.com
#要了解有关脱砖的的更多信息或联系我们的团队，请访问#https://debricked.com/
#                                                                                                                                                                   #
#要运行此工作流，请完成以下设置步骤：#
#                                                                                                                                                                   #
#1。如果您没有已拆分的帐户，请访问https://debricked.com/app/en/register#创建一个帐户
#2.按照https://portal.debricked.com/administration-47/how-do-i-generate-an-access-token-130#中提到的步骤生成已拆砖的访问令牌
#3.在GitHub中，导航到存储库#
#4.单击“设置”(如果看不到“设置”选项卡，请选择下拉菜单，然后单击“设置”)#
#5.在“安全性”部分，单击“机密和变量”，然后单击“操作”#
#6.在“密码”选项卡中，单击“新建存储库密码”#
#7.在“名称”字段中，键入密码的名称#
#8.在“密码”字段中，输入密码#的值
#9.点击“添加密码”#
#10.您现在应该可以使用工作流了！#
#####################################################################################################################################################################

姓名: 名称：去砖扫描

在……之上：
推：

权限:
内容: 读

作业：
漏洞扫描:
姓名: 漏洞扫描
连续的: ubuntu-最新

步骤：
      - uses: 操作/结帐@v4
-uses: 除砖/操作@v4
env:
DEBRICKED_TOKEN: ${{secrets.DEBRICKED_TOKEN}}
